version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/springboot-cicd/ # S3에서 받아올 프로젝트의 위치를 지정
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
